## Box Plot Graphs
attach(Book1)
boxplot(f3mArrest~maxtax, xlab = "maxtax", ylab = "f3mArrest")
boxplot(f3mArrest~maxunitstosell, xlab ="maxunitstosell" , ylab ="f3mArrest"  )
boxplot(f3mBrokeredDealerNotFoundBadDeals~maxsharedealprob,xlab ="maxsharedealprob " , ylab ="f3mBrokeredDealerNotFoundBadDeals ")
boxplot(f3mArrest~networkdegree,xlab ="networkdegreexlab " , ylab ="f3mArrest ")
boxplot(f3mBrokeredDealerNotFoundBadDeals~minsharedealprob,xlab ="minsharedealprob " , ylab ="f3mBrokeredDealerNotFoundBadDeals ")
boxplot(f3mArrest~policearrest,xlab ="policearrest" , ylab ="f3mArrest ")
boxplot(f3mBrokeredDealerNotFoundBadDeals~networkdegree,xlab ="networkdegree " , ylab ="f3mBrokeredDealerNotFoundBadDeals ")
boxplot(f3mBrokeredDealerNotFoundBadDeals~policearrest,xlab ="policearrest" , ylab ="f3mBrokeredDealerNotFoundBadDeals")
boxplot(f3mBrokeredDeals~maxsharedealprob,xlab ="maxsharedealprob " , ylab ="f3mBrokeredDeals ")
boxplot(f3mBrokeredDeals~minsharedealprob,xlab ="minsharedealprob " , ylab ="f3mBrokeredDeals ")
boxplot(f3mBrokeredDeals~policearrest,xlab ="policearrest " , ylab ="f3mBrokeredDeals ")
boxplot(f3mBrokeredDeals~networkdegree,xlab ="networkdegree " , ylab ="f3mBrokeredDeals ")
boxplot(f3mDirectDealerNotFoundBadDeals~maxunitstosell,xlab ="maxunitstosell " , ylab ="f3mDirectDealerNotFoundBadDeals ")
boxplot(f3mBrokeredUnSoldBadDeals~maxunitstosell,xlab ="maxunitstosell " , ylab ="f3mBrokeredUnSoldBadDeals ")
boxplot(f3mDirectDealerNotFoundBadDeals~maxtax,xlab ="maxtax " , ylab ="f3mDirectDealerNotFoundBadDeals ")
boxplot(f3mBrokeredUnSoldBadDeals~policearrest,xlab ="policearrest " , ylab ="f3mBrokeredUnSoldBadDeals ")
boxplot(f3mBrokeredUnSoldBadDeals~maxtax,xlab ="maxtax " , ylab ="f3mBrokeredUnSoldBadDeals ")
boxplot(f3mBrokeredUnSoldBadDeals~minunitstosell,xlab ="minunitstosell " , ylab ="f3mBrokeredUnSoldBadDeals ")
boxplot(f3mDirectDealerNotFoundBadDeals~minunitstosell,xlab ="minunitstosell " , ylab ="f3mDirectDealerNotFoundBadDeals ")
boxplot(f3mDirectDealerNotFoundBadDeals~policearrest,xlab ="policearrest " , ylab ="f3mDirectDealerNotFoundBadDeals ")
boxplot(f3mDirectDeals~networkdegree,xlab ="networkdegree " , ylab ="f3mDirectDeals ")
boxplot(f3mDirectDeals~minsharedealprob,xlab ="minsharedealprob " , ylab ="f3mDirectDeals ")
boxplot(f3mDirectDeals~maxsharedealprob,xlab ="maxsharedealprob " , ylab ="f3mDirectDeals ")
boxplot(f3mDirectUnSoldBadDeals~maxunitstosell,xlab ="maxunitstosell " , ylab ="f3mDirectUnSoldBadDeals ")
boxplot(f3mDirectUnSoldBadDeals~minunitstosell,xlab ="minunitstosell " , ylab ="f3mDirectUnSoldBadDeals ")
boxplot(f3mDirectDealerNotFoundBadDeals~maxtax,xlab ="maxtax " , ylab ="f3mDirectDealerNotFoundBadDeals ")
boxplot(f3mDirectDeals~policearrest,xlab ="policearrest " , ylab ="f3mDirectDeals ")
boxplot(f3mDirectUnSoldBadDeals~policearrest,xlab ="policearrest " , ylab ="f3mDirectUnSoldBadDeals ")
boxplot(f3mNoCustomer~maxsharedealprob,xlab ="maxsharedealprob " , ylab ="f3mNoCustomer ")
boxplot(f3mNoCustomer~networkdegree,xlab ="networkdegree " , ylab ="f3mNoCustomer ")

