library(readr)
try2 <- read_csv("C:/Users/Muhammad Shoaib Khan/Desktop/try2/try2.csv")
View(try2)
attach(try2)
boxplot(`count dealers`,main = "Count Dealers Boxplot")
boxplot(`count dealers`~arrests, main = "Count Dealers ~ arrests boxplot")
plot(`count dealers`~arrests,main = "Count Dealers ~ arrests scatter plot")
barplot(`count dealers`, main = "Barplot of count dealers")
barplot(arrests, main = "Barplot of arrests")
hist(`count dealers`)
hist(arrests)
