library(readr)
try3 <- read_csv("C:/Users/Muhammad Shoaib Khan/Desktop/try2/Wolfsheep3.csv")
View(try3)
attach(try3)
boxplot(`count wolves`~`count sheep`)
plot(`count wolves`)
plot(`count sheep`)
hist(`count sheep`)
hist(`count wolves`)
barplot(`count sheep`)
barplot(`count wolves`)
plot(`count wolves`~`count sheep`)
